server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yide?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  freemarker:
    suffix: .html
    template-loader-path: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
